application:
  commands:
    quit:
      name: quit
    add:
      name: add
    toggle:
      name: toggle
    delete:
      name: delete
    edit:
      name: edit
    print:
      name: print
      arg: all
    search:
      name: search
    unknown:
      name: unknownCommand